### ISSUE TITLE
Consider using SassDoc

### ISSUE THREAD

**Issue by HugoGiraudel** [ericam/true#23]
I don't see any documentation system currently in used for True. 

If you want to give [SassDoc](http://sassdoc.com) a try, I am cool with writing all the comments in a pull request. Just tell me.

**Comment by ericam** [comment]
I would be interested. Thanks!

**Comment by HugoGiraudel** [comment]
I'll do it. ;)

**Comment by HugoGiraudel** [comment]
I recommend you move the SassDoc generated documentation somewhere in the `gh-pages` branch?

**Comment by HugoGiraudel** [comment]
I suppose we can close. :)
