### ISSUE TITLE
Libsass support?

### ISSUE THREAD

**Issue by bgriffith** [ericam/true#26]
Hey, this is a really great project. I can get it working great with ruby sass but as all our projects are now using Libsass, is there any way to get it working with it?

When I try to compile with the latest Libsass and by using node-sass 2.0.1 & grunt-sass 18.0.0, I get the following;

```
Running "sass:test" (sass) task
>> optional parameters may not be combined with variable-length parameters
>>   Line 55  Column 3  bower_components/true/sass/true/_assert.scss
Warning:  Use --force to continue.

Aborted due to warnings.
```
Any ideas / info / suggestions?

**Comment by ericam** [comment]
Upgrade to the beta release of True. `2.2.0-beta` supports libsass.

**Comment by bgriffith** [comment]
Great thanks! Works perfect now - keep it up!

**Comment by greaterweb** [comment]
@ericam are you able to provide an update as to the status of 2.0.0 and when we might expect it to come out of beta?

Thanks!

**Comment by rootical** [comment]
@greaterweb, @ericam hands up. We are waiting for it.

**Comment by ericam** [comment]
Yes, sorry - released it over the weekend! More upgrades on the way...

**Comment by greaterweb** [comment]
Thank you for your efforts @ericam, much appreciated!
