### ISSUE TITLE
Error when running failing tests with true-cli

### ISSUE THREAD

**Issue by utis** [ericam/true#34]
If an assertion in a test fails, running the test with true-cli runs into an obscure error rather than providing useful information. Example:

    @import "true";

    @include test-module('An example') {
        @include test('foo-bar [mixin]') {
        @include assert-equal(1, 2, 'lala');
        }
    }

    @include report(true);

Running this with true-cli yields:

    ./src/contrib/true/bin/true-cli:62:in `match': invalid byte sequence in US-ASCII (ArgumentError)
        from ./src/contrib/true/bin/true-cli:62:in `match'
        from ./src/contrib/true/bin/true-cli:62:in `<main>' 

There are no non-ASCII characters in any of the involved files.

**Comment by ericam** [comment]
@scottdavis Can you look into this?
