### ISSUE TITLE
Problems getting working with eyeglass modules.

### ISSUE THREAD

**Issue by DominicBarnard** [ericam/true#35]
Trying to get this working with a sass library that imports eyeglass modules I've come across a couple of problems.  I've set up a [minimum project to test this out](https://github.com/DominicBarnard/test-true-eyeglass).

Mainly the problem is that the eyeglass custom importer function which resolves import statements loads files asynchronously which conflicts with true using sass renderSync causing errors.
I think the solution is to try enabling async testing with true to solve this problem.  This also adds the benefit of being able to test against eyegless modules which expose javascript functions to sass files which I understand also have the possibility of executing asyncly.

I'm looking at forking and trying to fix this for use with my own project but in case I'm missing something obvious that nullifies this issue any guidance is appreciated.

Also while I'm at it I've noticed the current eyeglass settings seem a little confused:
- True is currently set up to be imported by eyeglass as "sass-true" though the main sass file is named "true.scss" which i believe will not be picked up by eyeglass?
- Setting up true to be imported by eyeglass is not required as it adds itself to the sass includes before executing sass render anyway.

Again please let me know if I'm missing something otherwise I'll try and come up with something cleaner and submit a PR.

**Comment by chriseppstein** [comment]
Investigating. https://github.com/ericam/true/commit/b569be3bf3681b147d03538e460fc484d102e552 fixes the `@import` naming issue.

**Comment by DominicBarnard** [comment]
how about something like this [da2a60f7](https://github.com/DominicBarnard/true/commit/da2a60f7b8e5e72ef2208cb39d34d0fb28d69fc7)

**Comment by DominicBarnard** [comment]
If we pull out the section that prints the results and make it available as a separate method it's more flexible for different scenarios because you can render the tests to css anyway you like (maybe manipulate them for some reason) then just have the results printed out which is the main purpose of the module in the end.

**Comment by DominicBarnard** [comment]
[my attempt](https://github.com/ericam/true/pull/36)

**Comment by DominicBarnard** [comment]
issue is with https://github.com/sass/node-sass/issues/997

**Comment by yoannisj** [comment]
I am experiencing related issues with [importOnce](https://github.com/at-import/node-sass-import-once), which does async importing and therefore doesn't play well with sass-true.

As @DominicBarnard points out, this seems to be because of the [node-sass issue](https://github.com/sass/node-sass/issues/997) that  makes asynchronous importers not support `renderSync`, but that issue has been closed without a fix.

Is there anyway to make asynchronous importers such as [importOnce](https://github.com/at-import/node-sass-import-once) work with sass-true?

**Comment by mirisuzanne** [comment]
This is outside my expertise. @chriseppstein do you have thoughts? (Also: Should this be a new issue?)
