### ISSUE TITLE
True with jasmine

### ISSUE THREAD

**Issue by prisis** [ericam/true#40]
Hey :),
can someone tell me, how i can use true with jasmine?

**Comment by carljm** [comment]
Because `describe` and `it` are used the same in Jasmine as in Mocha, the Mocha example should Just Work if you run it with Jasmine instead. If not, you may need to dig into the `runSass` implementation to figure out how it needs to be adapted to work with Jasmine, and submit a PR.

**Comment by prisis** [comment]
Okay, I will try tomorrow :)
